# -*- coding: utf-8 -*-

"""
    smsapi.models.send_sms

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""


class SendSMS(object):

    """Implementation of the 'SendSMS' model.

    TODO: type model description here.

    Attributes:
        to (string): Phone number to send sms to
        body (string): Text body message

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "to" : "to",
        "body" : "body"
    }

    def __init__(self,
                 to=None,
                 body=None):
        """Constructor for the SendSMS class"""

        # Initialize members of the class
        self.to = to
        self.body = body


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        to = dictionary.get("to")
        body = dictionary.get("body")

        # Return an object of this model
        return cls(to,
                   body)


