# -*- coding: utf-8 -*-

"""
    smsapi.models.status_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class StatusEnum(object):

    """Implementation of the 'Status' enum.

    TODO: type enum description here.

    Attributes:
        PEND: TODO: type description here.
        SENT: TODO: type description here.
        DELIVRD: TODO: type description here.
        READ: TODO: type description here.

    """

    PEND = 'PEND'

    SENT = 'SENT'

    DELIVRD = 'DELIVRD'

    READ = 'READ'

