# -*- coding: utf-8 -*-

"""
    smsapi.smsapi_client

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""
from .decorators import lazy_property
from .configuration import Configuration
from .controllers.sms_controller import SMSController

class SmsapiClient(object):

    config = Configuration

    @lazy_property
    def sms(self):
        return SMSController()



